addMaterial("Steel", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 0, purifiedOre: 0, impureDust: 0, sawBlade: 1});
addMaterial("Rubber", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 1, crushedOre: 0, purifiedOre: 0, impureDust: 0, sawBlade: 0});
addMaterial("Copper", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Iron", {ingot: 0, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 1});
addMaterial("Lead", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Gold", {ingot: 0, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 1});
addMaterial("Tin", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 1, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Silver", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 1});
addMaterial("Bronze", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 0, purifiedOre: 0, impureDust: 0, sawBlade: 1});
addMaterial("Antimony", {ingot: 1, nugget: 1, longrod: 1, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 1, bolt: 1, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("LapisLazuli", {ingot: 0, nugget: 0, longrod: 0, plate: 1, dust: 1, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Redstone", {ingot: 0, nugget: 0, longrod: 0, plate: 1, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Diamond", {ingot: 0, nugget: 0, longrod: 0, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addGems("Diamond");
addMaterial("Emerald", {ingot: 0, nugget: 0, longrod: 0, plate: 1, dust: 1, smalldust: 1, tinydust: 1, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addGems("Emerald");
IDRegistry.genItemID("Lignite");
Item.createItem("Lignite", "Lignite", {name: "Lignite"});
addMaterial("Lignite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 1, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Coal", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 1, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 1, impureDust: 1, sawBlade: 0});
addMaterial("Cassiterite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("BrownLimonite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("YellowLimonite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("BandedIron", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Malachite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Magnetite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("VanadiumMagnetite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Chalcopyrite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Pyrite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Tetrahedrite", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Galena", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 0, smalldust: 0, tinydust: 0, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 1, purifiedOre: 0, impureDust: 1, sawBlade: 0});
addMaterial("Ashes", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 1, smalldust: 0, tinydust: 1, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 0, purifiedOre: 0, impureDust: 0, sawBlade: 0});
addMaterial("DarkAshes", {ingot: 0, nugget: 0, longrod: 0, plate: 0, dust: 1, smalldust: 0, tinydust: 1, rod: 0, bolt: 0, screw: 0, smallGear: 0, Gear: 0, foil: 0, ring: 0, crushedOre: 0, purifiedOre: 0, impureDust: 0, sawBlade: 0});

IDRegistry.genItemID("dustStone");
Item.createItem("dustStone", "Stone Dust", {name: "STONE_DUST"});

IDRegistry.genItemID("impureDustStone");
Item.createItem("impureDustStone", "Impure Stone Dust", {name: "IMPURE_STONE_DUST"});